#!/usr/bin/env bash

# update ssh remote
echo "update yadm repo origin"
yadm remote set-url origin "git@github.com:pilina/dotfiles.git"

# install oh-my-bash
export OSH="$HOME/.config/oh-my-bash"
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
