#!/usr/bin/env bash

# update ssh remote
echo "update yadm repo origin"
yadm remote set-url origin "git@github.com:pilina/dotfiles.git"

# install bash-it
git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.config/bash_it
~/.config/bash_it/install.sh --silent --no-modify-config
